const IMAGE_FOLDER = "/company_logos";

export const company_data = [
  {
    name: "All Foods",
    image: `${IMAGE_FOLDER}`,
    type: ["Agri-food corp industry"],
    known_affiliations: ["Holt Coalition", "Biotechnica"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Allworld Insurance",
    image: `${IMAGE_FOLDER}`,
    type: ["Insurance business"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Arasaka",
    image: `${IMAGE_FOLDER}`,
    type: ["Corporate security", "Manufacturing", "Banking"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Archer",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Avante",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons manufacturer", "Clothing brand & store chain"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Biotechnica",
    image: `${IMAGE_FOLDER}`,
    type: [
      "Genetic engineering",
      "Microbiological research",
      "Biochemical research",
    ],
    known_affiliations: ["Petrochem", "Arasaka"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Braindance Inc.",
    image: `${IMAGE_FOLDER}`,
    type: ["Entertainment"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Brennan",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Budget Arms",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Chevillon",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Combat Cab",
    image: `${IMAGE_FOLDER}`,
    type: ["Taxi company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Constitutional Arms",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Corp-Bud",
    image: `${IMAGE_FOLDER}`,
    type: ["Construction company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Dakai Soundsystems",
    image: `${IMAGE_FOLDER}`,
    type: ["Vocal Cyberware", "Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Darra Polytechnic",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Data Inc.",
    image: `${IMAGE_FOLDER}`,
    type: ["Electronics manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Delamain Corporation",
    image: `${IMAGE_FOLDER}`,
    type: ["Taxi company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Dynalar",
    image: `${IMAGE_FOLDER}`,
    type: ["Cybernetic Technology"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Fuyutsuki Electronics",
    image: `${IMAGE_FOLDER}`,
    type: ["Electronics Manufacturer", "Electronics Store"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Hydrosubsidium",
    image: `${IMAGE_FOLDER}`,
    type: ["Underwater technologies"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Jinguji",
    image: `${IMAGE_FOLDER}`,
    type: ["Clothing brand & store chain"],
    known_affiliations: ["Arasaka"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kang Tao",
    image: `${IMAGE_FOLDER}`,
    type: ["Corporate Weapons Manufacturer", "Weapons Manufacturer"],
    known_affiliations: ["QianT"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kaukaz",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kendachi",
    image: `${IMAGE_FOLDER}`,
    type: ["Arms Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kiroshi",
    image: `${IMAGE_FOLDER}`,
    type: ["Optics Manufacturing", "Cyberware Manufacturing"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Macroware",
    image: `${IMAGE_FOLDER}`,
    type: ["Video game developer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Mahir Motors",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Makigai",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "MaxiWear",
    image: `${IMAGE_FOLDER}`,
    type: ["Leisurewear brand"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Militech",
    image: `${IMAGE_FOLDER}`,
    type: [
      "Arms manufacturing",
      "Military vehicle production",
      "Mercenary contracting",
    ],
    known_affiliations: ["NUSA"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Mizutani",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "MoorE Technologies",
    image: `${IMAGE_FOLDER}`,
    type: ["Cyberware Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Nokota",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Orbital Air",
    image: `${IMAGE_FOLDER}`,
    type: [
      "Cargo transport to Earth orbit",
      "Passenger transport to Earth orbit",
      "Maintenance of commercial orbital facilities",
    ],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Petrochem",
    image: `${IMAGE_FOLDER}`,
    type: ["Petrochemical products", "Agribusiness"],
    known_affiliations: ["Biotechnica"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Planetran",
    image: `${IMAGE_FOLDER}`,
    type: ["Railway transport"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Quadra",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: ["Dayton"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Rayfield",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Revere Courier Services",
    image: `${IMAGE_FOLDER}`,
    type: ["Shipping business"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Rostović",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Thorton",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Trauma Team",
    image: `${IMAGE_FOLDER}`,
    type: ["Ambulance Paramedica"],
    known_affiliations: ["Delamain Corporation"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Tsunami",
    image: `${IMAGE_FOLDER}`,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Villefort",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Yaiba",
    image: `${IMAGE_FOLDER}`,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Zetatech",
    image: `${IMAGE_FOLDER}`,
    type: [
      "Wetware",
      "computer hardware",
      "software design",
      "heavy machinery",
      "transportation",
      "shipping",
    ],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
];
