import allFoodsLogo from "@/assets/company_logos/All-Foods.png";
import allWorldsInsuranceLogo from "@/assets/company_logos/All-Worlds-Insurance.png";
import arasakaLogo from "@/assets/company_logos/Arasaka.png";
import archerLogo from "@/assets/company_logos/Archer.png";
import avanteLogo from "@/assets/company_logos/Avante.png";
import biotechnicaLogo from "@/assets/company_logos/Biotechnica.png";
import braindanceLogo from "@/assets/company_logos/Braindance.png";
import brennanLogo from "@/assets/company_logos/Brennan.png";
import budgetArmsLogo from "@/assets/company_logos/Budget-Arms.png";
import chevillonLogo from "@/assets/company_logos/Chevillon.png";
import constitutionalArmsLogo from "@/assets/company_logos/Constitutional-Arms.png";
import corpBudLogo from "@/assets/company_logos/Cop-Bud.png";
import dakaiLogo from "@/assets/company_logos/Dakai.png";
import darraPolytechnicLogo from "@/assets/company_logos/Darra-Polytechnic.png";
import dataIncLogo from "@/assets/company_logos/Data-Inc.png";
import delamainTaxiLogo from "@/assets/company_logos/Delamain-Taxi.png";
import dynalarLogo from "@/assets/company_logos/Dynalar.png";
import fuyutsukiLogo from "@/assets/company_logos/Fuyutsuki.png";
import hydroSubsidiumLogo from "@/assets/company_logos/Hydro-Subsidium.png";
import jingujiLogo from "@/assets/company_logos/Junguji.png";
import kangTaoLogo from "@/assets/company_logos/Kang-Tao.png";
import kaukazLogo from "@/assets/company_logos/Kaukaz.png";
import kendachiLogo from "@/assets/company_logos/Kendachi.png";
import kiroshiLogo from "@/assets/company_logos/Kiroshi.png";
import macrowareLogo from "@/assets/company_logos/Macroware.png";
import mahirMotorsLogo from "@/assets/company_logos/Mahir.png";
import makigaiLogo from "@/assets/company_logos/Makigai.png";
import maxiWearLogo from "@/assets/company_logos/Maxiwear.png";
import militechLogo from "@/assets/company_logos/Militech.png";
import mizutaniLogo from "@/assets/company_logos/Mizutani.png";
import mooreTechnologiesLogo from "@/assets/company_logos/Moore.png";
import nokotaLogo from "@/assets/company_logos/Nokota.png";
import orbitalAirLogo from "@/assets/company_logos/Orbital-Air.png";
import petrochemLogo from "@/assets/company_logos/Petrochem.png";
import planetranLogo from "@/assets/company_logos/Planetran.png";
import rayfieldLogo from "@/assets/company_logos/Rayfield.png";
import revereCourierServicesLogo from "@/assets/company_logos/RCS.png";
import rostovicLogo from "@/assets/company_logos/Rostovic.png";
import thortonLogo from "@/assets/company_logos/Thorton.png";
import traumaTeamLogo from "@/assets/company_logos/Trauma-Team.png";
import tsunamiLogo from "@/assets/company_logos/Tsunami.png";
import villefortLogo from "@/assets/company_logos/Villefort.png";
import yaibaLogo from "@/assets/company_logos/Yaiba.png";
import zetatechLogo from "@/assets/company_logos/Zetatech.png";

export interface Company {
  name: string;
  image: any;
  type: Array<string>;
  known_affiliations: Array<string>;
  current_share_value: number;
  meta_values: {
    Open: number;
    High: number;
    Low: number;
    Mkt_cap: number;
    P_E_ratio: number;
    Div_yield: number;
    CDP_score: number;
    wk_52_high: number;
    wk_52_low: number;
  };
  trending: number;
}

export const company_data = [
  {
    name: "All Foods",
    image: allFoodsLogo,
    type: ["Agri-food corp industry"],
    known_affiliations: ["Holt Coalition", "Biotechnica"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Allworld Insurance",
    image: allWorldsInsuranceLogo,
    type: ["Insurance business"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Arasaka",
    image: arasakaLogo,
    type: ["Corporate security", "Manufacturing", "Banking"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Archer",
    image: archerLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Avante",
    image: avanteLogo,
    type: ["Weapons manufacturer", "Clothing brand", "Store chain"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Biotechnica",
    image: biotechnicaLogo,
    type: [
      "Genetic engineering",
      "Microbiological research",
      "Biochemical research",
    ],
    known_affiliations: ["Petrochem", "Arasaka"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Braindance Inc.",
    image: braindanceLogo,
    type: ["Entertainment"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Brennan",
    image: brennanLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Budget Arms",
    image: budgetArmsLogo,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Chevillon",
    image: chevillonLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Combat Cab",
    image: "",
    type: ["Taxi company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Constitutional Arms",
    image: constitutionalArmsLogo,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Corp-Bud",
    image: corpBudLogo,
    type: ["Construction company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Dakai Soundsystems",
    image: dakaiLogo,
    type: ["Vocal Cyberware", "Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Darra Polytechnic",
    image: darraPolytechnicLogo,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Data Inc.",
    image: dataIncLogo,
    type: ["Electronics manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Delamain Corporation",
    image: delamainTaxiLogo,
    type: ["Taxi company"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Dynalar",
    image: dynalarLogo,
    type: ["Cybernetic Technology"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Fuyutsuki Electronics",
    image: fuyutsukiLogo,
    type: ["Electronics Manufacturer", "Electronics Store"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Hydrosubsidium",
    image: hydroSubsidiumLogo,
    type: ["Underwater technologies"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Jinguji",
    image: jingujiLogo,
    type: ["Clothing brand & store chain"],
    known_affiliations: ["Arasaka"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kang Tao",
    image: kangTaoLogo,
    type: ["Corporate Weapons Manufacturer", "Weapons Manufacturer"],
    known_affiliations: ["QianT"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kaukaz",
    image: kaukazLogo,
    type: ["Vehicle Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kendachi",
    image: kendachiLogo,
    type: ["Arms Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Kiroshi",
    image: kiroshiLogo,
    type: ["Optics Manufacturing", "Cyberware Manufacturing"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Macroware",
    image: macrowareLogo,
    type: ["Video game developer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Mahir Motors",
    image: mahirMotorsLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Makigai",
    image: makigaiLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "MaxiWear",
    image: maxiWearLogo,
    type: ["Leisurewear brand"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Militech",
    image: militechLogo,
    type: [
      "Arms manufacturing",
      "Military vehicle production",
      "Mercenary contracting",
    ],
    known_affiliations: ["NUSA"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Mizutani",
    image: mizutaniLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "MoorE Technologies",
    image: mooreTechnologiesLogo,
    type: ["Cyberware Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Nokota",
    image: nokotaLogo,
    type: ["Weapons manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Orbital Air",
    image: orbitalAirLogo,
    type: [
      "Cargo transport to Earth orbit",
      "Passenger transport to Earth orbit",
      "Maintenance of commercial orbital facilities",
    ],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Petrochem",
    image: petrochemLogo,
    type: ["Petrochemical products", "Agribusiness"],
    known_affiliations: ["Biotechnica"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Planetran",
    image: planetranLogo,
    type: ["Railway transport"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Quadra",
    image: "",
    type: ["Vehicle manufacturer"],
    known_affiliations: ["Dayton"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Rayfield",
    image: rayfieldLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Revere Courier Services",
    image: revereCourierServicesLogo,
    type: ["Shipping business"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Rostović",
    image: rostovicLogo,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Thorton",
    image: thortonLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Trauma Team",
    image: traumaTeamLogo,
    type: ["Ambulance Paramedica"],
    known_affiliations: ["Delamain Corporation"],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Tsunami",
    image: tsunamiLogo,
    type: ["Weapons Manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Villefort",
    image: villefortLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Yaiba",
    image: yaibaLogo,
    type: ["Vehicle manufacturer"],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
  {
    name: "Zetatech",
    image: zetatechLogo,
    type: [
      "Wetware",
      "computer hardware",
      "software design",
      "heavy machinery",
      "transportation",
      "shipping",
    ],
    known_affiliations: [],
    current_share_value: 0,
    meta_values: {
      Open: 0,
      High: 0,
      Low: 0,
      Mkt_cap: 0,
      P_E_ratio: 0,
      Div_yield: 0,
      CDP_score: 0,
      wk_52_high: 0,
      wk_52_low: 0,
    },
    trending: 0,
  },
];
